return {
	"stevearc/conform.nvim",
	event = { "BufReadPre", "BufReadPost", "BufNewFile" },
	opts = {
		format = {
			timeout_ms = 500,
			lsp_fallback = true,
			async = false,
		},

		formatters_by_ft = {
			javascript = { { "eslint_d", "prettierd" } },
			typescript = { { "eslint_d", "prettierd" } },
			typescriptreact = { { "eslint_d", "prettierd" } },
			javascriptreact = { { "eslint_d", "prettierd" } },
			json = { "prettierd" },
			yaml = { "prettierd" },
			markdown = { "prettierd" },
			graphql = { "prettierd" },
			scss = { { "stylelint", "prettierd" } },
			css = { { "stylelint", "prettierd" } },
			html = { "prettierd" },
			lua = { "stylua" },
			fish = { "fish_indent" },
			sh = { "shfmt" },
			zsh = { "shfmt" },
			python = { "isort", "black" },
			["*"] = { "codespell" },
			["_"] = { "trim_whitespace" },
		},
		formatters = {
			prettierd = {
				command = "prettierd",
				args = { "--stdin-filepath", vim.api.nvim_buf_get_name(0) },
				rootPatterns = {
					".prettierrc",
					".prettierrc.json",
					".prettierrc.toml",
					".prettierrc.js",
					".prettierrc.cjs",
					".prettierrc.json5",
					".prettierrc.yaml",
					".prettierrc.yml",
					"prettier.config.js",
					"prettier.config.cjs",
					"prettier.config.mjs",
					".editorconfig",
				},
			},
		},
	},
}
