local M = {}

-- Go: "// Code generated by protoc-gen"
local function is_go_proto_generated(path)
	if not path:match("%.go$") then return false end
	local f = io.open(path, "r")
	if not f then return false end
	local first = f:read("*l") or ""
	f:close()
	return first:match("Code generated by protoc%-gen") ~= nil
end

-- TS: "*_pb.ts" with @generated header
local function is_ts_proto_generated(path)
	if not path:match("_pb%.ts$") then return false end
	local f = io.open(path, "r")
	if not f then return false end
	local first = f:read("*l") or ""
	f:close()
	return first:match("@generated by protoc%-gen") ~= nil
end

local function get_proto_source_go(path)
	local lines = vim.fn.readfile(path, "", 15)
	for _, line in ipairs(lines) do
		line = line:gsub("\r", "")
		local source = line:match("^// source: (.+)")
		if source then return source:gsub("[\r\n%s]+$", "") end
	end
	return nil
end

-- "// @generated from file foo.proto (package v1, syntax proto3)"
local function get_proto_source_ts(path)
	local lines = vim.fn.readfile(path, "", 5)
	for _, line in ipairs(lines) do
		local source = line:match("@generated from file (.+%.proto)")
		if source then return source end
	end
	return nil
end

local function find_proto_file(source_path)
	source_path = source_path:gsub("[\r\n]", "")
	local filename = source_path:match("([^/]+)$")

	local basename = filename:gsub("%.[^.]*$", "")
	local candidates = { filename }
	local proto_fallback = basename .. ".proto"
	if proto_fallback ~= filename then table.insert(candidates, proto_fallback) end

	local roots = vim.lsp.buf.list_workspace_folders()
	table.insert(roots, vim.fn.getcwd())

	for _, candidate in ipairs(candidates) do
		for _, root in ipairs(roots) do
			local result = vim.fn.findfile(candidate, root .. "/**")
			if result ~= "" then return vim.fn.fnamemodify(result, ":p") end
		end
	end
	return nil
end

local function find_symbol_line(proto_path, symbol)
	local lines = vim.fn.readfile(proto_path)
	if not lines or #lines == 0 then return nil end

	local function search_from(from, pat)
		for i = from, #lines do
			if lines[i]:match(pat) then return i end
		end
		return nil
	end

	local escaped = vim.pesc(symbol)

	local function make_patterns(keyword, name)
		return {
			"^%s*" .. keyword .. "%s+" .. name .. "[%s{(]",
			"^%s*" .. keyword .. "%s+" .. name .. "$",
		}
	end

	for _, pair in ipairs({
		{ "message", escaped }, { "enum", escaped },
		{ "rpc",     escaped }, { "service", escaped },
	}) do
		for _, p in ipairs(make_patterns(pair[1], pair[2])) do
			local lnum = search_from(1, p)
			if lnum then return lnum end
		end
	end

	-- Go nested naming: TypeA_TypeB → find "message TypeA" then "message TypeB"
	local parts = {}
	for part in symbol:gmatch("[^_]+") do table.insert(parts, part) end
	if #parts >= 2 then
		for _, p in ipairs(make_patterns("message", vim.pesc(parts[1]))) do
			local top = search_from(1, p)
			if top then
				for _, np in ipairs(make_patterns("message", vim.pesc(parts[#parts]))) do
					local lnum = search_from(top + 1, np)
					if lnum then return lnum end
				end
				break
			end
		end
	end

	return nil
end

local function camel_to_snake(s)
	s = s:gsub("(%u+)(%u%l)", "%1_%2")
	s = s:gsub("(%l%d*)(%u)", "%1_%2")
	return s:lower()
end

local function find_field_line(lines, from_line, field_name)
	local escaped = vim.pesc(field_name)
	for i = from_line + 1, #lines do
		local l = lines[i]
		if l:match("^message%s") or l:match("^service%s") or l:match("^enum%s") then break end
		if l:match("%s" .. escaped .. "%s*=") then return i end
	end
	return nil
end

local function get_pb_receiver_type(fname, lnum)
	local lines = vim.fn.readfile(fname, "", lnum + 1)
	if not lines then return nil end
	for i = math.min(lnum, #lines), math.max(1, lnum - 3), -1 do
		local receiver = (lines[i] or ""):match("^func %([^*]*%*([%w_]+)%)")
		if receiver then return receiver end
	end
	return nil
end

local function jump_to_proto(fname, symbol, item)
	local source
	if is_go_proto_generated(fname) then
		source = get_proto_source_go(fname)
	elseif is_ts_proto_generated(fname) then
		source = get_proto_source_ts(fname)
	else
		return false
	end

	if not source then
		vim.notify("proto-jump: no source comment in " .. vim.fn.fnamemodify(fname, ":t"), vim.log.levels.WARN)
		return true
	end

	local proto_path = find_proto_file(source)
	if not proto_path then
		vim.notify("proto-jump: proto file not found: " .. source, vim.log.levels.WARN)
		return true
	end

	local lnum = find_symbol_line(proto_path, symbol)

	-- TS camelCase → PascalCase: "listFoo" → "ListFoo"
	if not lnum and is_ts_proto_generated(fname) then
		local pascal = symbol:sub(1, 1):upper() .. symbol:sub(2)
		if pascal ~= symbol then lnum = find_symbol_line(proto_path, pascal) end
	end

	-- Go getter fallback: GetFoo → find field in receiver message
	if not lnum and symbol:match("^Get[A-Z]") and is_go_proto_generated(fname) then
		local receiver = get_pb_receiver_type(fname, item.lnum or 1)
		if receiver then
			local message_lnum = find_symbol_line(proto_path, receiver)
			if message_lnum then
				local proto_lines = vim.fn.readfile(proto_path)
				local field_name = camel_to_snake(symbol:gsub("^Get", ""))
				lnum = find_field_line(proto_lines, message_lnum, field_name) or message_lnum
			end
		end
	end

	vim.cmd("edit " .. vim.fn.fnameescape(proto_path))
	vim.api.nvim_win_set_cursor(0, { lnum or 1, 0 })
	vim.cmd("normal! zz")
	return true
end

function M.goto_definition()
	local symbol = vim.fn.expand("<cword>")

	vim.lsp.buf.definition({
		on_list = function(opts)
			if not opts or not opts.items or #opts.items == 0 then return end

			local item = opts.items[1]
			local fname = item.filename or (item.uri and vim.uri_to_fname(item.uri))
			if not fname then return end

			if jump_to_proto(fname, symbol, item) then return end

			-- fallback: standard LSP jump
			if #opts.items == 1 then
				vim.cmd("edit " .. vim.fn.fnameescape(fname))
				vim.api.nvim_win_set_cursor(0, { item.lnum or 1, math.max(0, (item.col or 1) - 1) })
			else
				vim.fn.setqflist({}, " ", opts)
				vim.cmd("cfirst")
			end
		end,
	})
end

function M.setup()
	vim.api.nvim_create_autocmd("LspAttach", {
		group = vim.api.nvim_create_augroup("proto-jump", { clear = true }),
		callback = function(event)
			local ft = vim.bo[event.buf].filetype
			if ft == "go" or ft == "typescript" or ft == "typescriptreact" then
				vim.keymap.set("n", "gd", M.goto_definition, { buffer = event.buf, desc = "Goto Definition (proto-aware)" })
			end
		end,
	})
end

return M
