local M = {}

local function is_proto_generated(path)
	if not path:match("%.go$") then return false end
	local f = io.open(path, "r")
	if not f then return false end
	local first = f:read("*l") or ""
	f:close()
	return first:match("Code generated by protoc%-gen") ~= nil
end

local function get_proto_source(path)
	local f = io.open(path, "r")
	if not f then return nil end
	local source
	for _ = 1, 15 do
		local line = f:read("*l")
		if not line then break end
		source = line:match("^// source: (.+)$")
		if source then break end
	end
	f:close()
	return source
end

local function find_proto_file(source_path)
	local roots = vim.lsp.buf.list_workspace_folders()
	table.insert(roots, vim.fn.getcwd())
	for _, root in ipairs(roots) do
		local full = root .. "/" .. source_path
		if vim.fn.filereadable(full) == 1 then
			return full
		end
	end
	return nil
end

local function find_symbol_line(proto_path, symbol)
	local escaped = vim.pesc(symbol)
	local patterns = {
		"^%s*message%s+" .. escaped .. "%s*[{%s]",
		"^%s*enum%s+" .. escaped .. "%s*[{%s]",
		"^%s*rpc%s+" .. escaped .. "%s*[(%s]",
		"^%s*service%s+" .. escaped .. "%s*[{%s]",
	}
	local lnum = 0
	for line in io.lines(proto_path) do
		lnum = lnum + 1
		for _, p in ipairs(patterns) do
			if line:match(p) then
				return lnum
			end
		end
	end
	return nil
end

function M.goto_definition()
	local symbol = vim.fn.expand("<cword>")

	vim.lsp.buf.definition({
		on_list = function(opts)
			if not opts or not opts.items or #opts.items == 0 then return end

			local item = opts.items[1]
			local fname = item.filename or (item.uri and vim.uri_to_fname(item.uri))

			if fname and is_proto_generated(fname) then
				local source = get_proto_source(fname)
				if source then
					local proto_path = find_proto_file(source)
					if proto_path then
						local lnum = find_symbol_line(proto_path, symbol) or 1
						vim.cmd("edit " .. vim.fn.fnameescape(proto_path))
						vim.api.nvim_win_set_cursor(0, { lnum, 0 })
						vim.cmd("normal! zz")
						return
					end
				end
			end

			-- fallback: standard jump
			if #opts.items == 1 then
				vim.cmd("edit " .. vim.fn.fnameescape(fname))
				vim.api.nvim_win_set_cursor(0, { item.lnum or 1, math.max(0, (item.col or 1) - 1) })
			else
				vim.fn.setqflist({}, " ", opts)
				vim.cmd("cfirst")
			end
		end,
	})
end

return M
