-- return {
-- 	"akinsho/bufferline.nvim",
-- 	event = "BufEnter",
-- 	dependencies = { "nvim-mini/mini.bufremove" },
-- 	opts = {
-- 		options = {
-- 			close_command = function(n)
-- 				require("mini.bufremove").delete(n, false)
-- 			end,
-- 			diagnostics = "nvim_lsp",
-- 			always_show_bufferline = false,
-- 			diagnostics_indicator = function(_, _, diag)
-- 				local icons = require("lazyvim.config").icons.diagnostics
-- 				local ret = (diag.error and icons.Error .. diag.error .. " " or "")
-- 					.. (diag.warning and icons.Warn .. diag.warning or "")
-- 				return vim.trim(ret)
-- 			end,
-- 		},
-- 	},
-- 	config = function(_, opts)
-- 		require("bufferline").setup(opts)
-- 	end,
-- }
--
-- --highlights = require("catppuccin.groups.integrations.bufferline").get({style='default'})
